const departaments = [
  {
    "nombre": "Amazonas",
    "municipios": [
      "Leticia",
      "El encanto",
      "La chorrera",
      "La pedrera",
      "La victoria",
      "Mirita - Parana",
      "Puerto alegria",
      "Puerto arica",
      "Puerto nariño",
      "Puerto santander",
      "Tarapaca",
    ],
  },
  {
    "nombre": "Antioquia",
    // todos los "municipios" de la departamento de Antioquia
    "municipios": [
      "Abejorral",
      "Abriaquí",
      "Alejandría",
      "Amagá",
      "Amalfi",
      "Andes",
      "Angelópolis",
      "Angostura",
      "Anorí",
      "Anzá",
      "Apartadó",
      "Arboletes",
      "Argelia",
      "Armenia",
      "Barbosa",
      "Bello",
      "Belmira",
      "Betania",
      "Betulia",
      "Briceño",
      "Buriticá",
      "Cáceres",
      "Caicedo",
      "Caldas",
      "Campamento",
      "Cañasgordas",
      "Caracolí",
      "Caramanta",
      "Carepa",
      "Carolina del Príncipe",
      "Caucasia",
      "Chigorodó",
      "Cisneros",
      "Ciudad Bolívar",
      "Cocorná",
      "Concepción",
      "Concordia",
      "Copacabana",
      "Dabeiba",
      "Donmatías",
      "Ebéjico",
      "El Bagre",
      "El Carmen de Viboral",
      "El Peñol",
      "El Retiro",
      "El Santuario",
      "Entrerríos",
      "Envigado",
      "Fredonia",
      "Frontino",
      "Giraldo",
      "Girardota",
      "Gómez Plata",
      "Granada",
      "Guadalupe",
      "Guarne",
      "Guatapé",
      "Heliconia",
      "Hispania",
      "Itagüí",
      "Ituango",
      "Jardín",
      "Jericó",
      "La Ceja",
      "La Estrella",
      "La Pintada",
      "La Unión",
      "Liborina",
      "Maceo",
      "Marinilla",
      "Medellín",
      "Montebello",
      "Murindó",
      "Mutatá",
      "Nariño",
      "Nechí",
      "Necoclí",
      "Olaya",
      "Peque",
      "Pueblorrico",
      "Puerto Berrío",
      "Puerto Nare",
      "Puerto Triunfo",
      "Remedios",
      "Rionegro",
      "Sabanalarga",
      "Sabaneta",
      "Salgar",
      "San Andrés de Cuerquia",
      "San Carlos",
      "San Francisco",
      "San Jerónimo",
      "San José de la Montaña",
      "San Juan de Urabá",
      "San Luis",
      "San Pedro de los Milagros",
      "San Pedro de Urabá",
      "San Rafael",
      "San Roque",
      "San Vicente",
      "Santa Bárbara",
      "Santa Fe de Antioquia",
      "Santa Rosa de Osos",
      "Santo Domingo",
      "Segovia",
      "Sonsón",
      "Sopetrán",
      "Támesis",
      "Tarazá",
      "Tarso",
      "Titiribí",
      "Toledo",
      "Turbo",
      "Uramita",
      "Urrao",
      "Valdivia",
      "Valparaíso",
      "Vegachí",
      "Venecia",
      "Vigía del Fuerte",
      "Yalí",
      "Yarumal",
      "Yolombó",
      "Yondó",
      "Zaragoza",
    ],
  },
  {
    "nombre": "Arauca",
    // todos los "municipios" de la departamento de Arauca
    "municipios": [
      "Arauca",
      "Arauquita",
      "Cravo Norte",
      "Fortul",
      "Puerto rondon",
      "Saravena",
      "Tame",
    ],
  },
  {
    "nombre": "Atlántico",
    // todos los "municipios" de la departamento de Atlántico
    "municipios": [
      "Barranquilla",
      "Baranoa",
      "Campo de la Cruz",
      "Candelaria",
      "Galapa",
      "Juan de Acosta",
      "Luruaco",
      "Malambo",
      "Manatí",
      "Palmar de Varela",
      "Piojó",
      "Polonuevo",
      "Ponedera",
      "Puerto Colombia",
      "Repelón",
      "Sabanagrande",
      "Sabanalarga",
      "Santa Lucía",
      "Santo Tomás",
      "Soledad",
      "Suan",
      "Tubará",
      "Usiacurí",
    ],
  },
  {
    "nombre": "Bolívar",
    "municipios": [
      "Achí",
      "Altos del Rosario",
      "Arenal",
      "Arjona",
      "Arroyohondo",
      "Barranco de Loba",
      "Calamar",
      "Cantagallo",
      "El Carmen de Bolívar",
      "Cartagena de Indias",
      "Cicuco",
      "Clemencia",
      "Córdoba",
      "El Guamo",
      "El Peñón",
      "Hatillo de Loba",
      "Magangué",
      "Mahates",
      "Margarita",
      "María La Baja",
      "Montecristo",
      "Morales",
      "Norosí",
      "Pinillos",
      "Regidor",
      "Río Viejo",
      "San Cristóbal",
      "San Estanislao",
      "San Fernando",
      "San Jacinto",
      "San Jacinto del Cauca",
      "San Juan Nepomuceno",
      "San Martín de Loba",
      "San Pablo",
      "Santa Catalina",
      "Santa Cruz de Mompox",
      "Santa Rosa",
      "Santa Rosa del Sur",
      "Simití",
      "Soplaviento",
      "Talaigua Nuevo",
      "Tiquisio",
      "Turbaco",
      "Turbaná",
      "Villanueva",
      "Zambrano",
    ],
  },
  {
    "nombre": "Boyacá",
    "municipios": [
      "Chíquiza",
      "Chivatá",
      "Cómbita",
      "Cucaita",
      "Motavita",
      "Oicatá",
      "Samacá",
      "Siachoque",
      "Sora",
      "Soracá",
      "Sotaquirá",
      "Toca",
      "Tunja",
      "Tuta",
      "Ventaquemada",
      "Chiscas",
      "El Cocuy",
      "El Espino",
      "Guacamayas",
      "Güicán",
      "Panqueba",
      "Labranzagrande",
      "Pajarito",
      "Paya",
      "Pisba",
      "Berbeo",
      "Campohermoso",
      "Miraflores",
      "Páez",
      "San Eduardo",
      "Zetaquira",
      "Boyacá",
      "Ciénega",
      "Jenesano",
      "Nuevo Colón",
      "Ramiriquí",
      "Rondón",
      "Tibaná",
      "Turmequé",
      "Úmbita",
      "Viracachá",
      "Chinavita",
      "Garagoa",
      "Macanal",
      "Pachavita",
      "San Luis de Gaceno",
      "Santa María",
      "Boavita",
      "Covarachía",
      "La Uvita",
      "San Mateo",
      "Sativanorte",
      "Sativasur",
      "Soatá",
      "Susacón",
      "Tipacoque",
      "Briceño",
      "Buenavista",
      "Caldas",
      "Chiquinquirá",
      "Coper",
      "La Victoria",
      "Maripí",
      "Muzo",
      "Otanche",
      "Pauna",
      "Quípama",
      "Saboyá",
      "San Miguel de Sema",
      "San Pablo de Borbur",
      "Tununguá",
      "Almeida",
      "Chivor",
      "Guateque",
      "Guayatá",
      "La Capilla",
      "Somondoco",
      "Sutatenza",
      "Tenza",
      "Arcabuco",
      "Chitaraque",
      "Gachantivá",
      "Moniquirá",
      "Ráquira",
      "Sáchica",
      "San José de Pare",
      "Santa Sofía",
      "Santana",
      "Sutamarchán",
      "Tinjacá",
      "Togüí",
      "Villa de Leyva",
      "Aquitania",
      "Cuítiva",
      "Firavitoba",
      "Gámeza",
      "Iza",
      "Mongua",
      "Monguí",
      "Nobsa",
      "Pesca",
      "Sogamoso",
      "Tibasosa",
      "Tópaga",
      "Tota",
      "Belén",
      "Busbanzá",
      "Cerinza",
      "Corrales",
      "Duitama",
      "Floresta",
      "Paipa",
      "Santa Rosa de Viterbo",
      "Tutazá",
      "Betéitiva",
      "Chita",
      "Jericó",
      "Paz de Río",
      "Socha",
      "Socotá",
      "Tasco",
      "Cubará",
      "Puerto Boyacá",
    ],
  },
  {
    "nombre": "Caldas",
    "municipios": [
      "Filadelfia",
      "La Merced",
      "Marmato",
      "Riosucio",
      "Supía",
      "Manzanares",
      "Marquetalia",
      "Marulanda",
      "Pensilvania",
      "Anserma",
      "Belalcázar",
      "Risaralda",
      "San José",
      "Viterbo",
      "Chinchiná",
      "Manizales",
      "Neira",
      "Palestina",
      "Villamaría",
      "La Dorada",
      "Norcasia",
      "Samaná",
      "Victoria",
      "Aguadas",
      "Aranzazu",
      "Pácora",
      "Salamina",
    ],
  },
  {
    "nombre": "Caquetá",
    "municipios": [
      "Albania",
      "Belén de los Andaquíes",
      "Cartagena del Chairá",
      "Curillo",
      "El Doncello",
      "El Paujil",
      "Florencia",
      "La Montañita",
      "Morelia",
      "Puerto Milán",
      "Puerto Rico",
      "San José del Fragua",
      "San Vicente del Caguán",
      "Solano",
      "Solita",
      "Valparaíso",
    ],
  },
  {
    "nombre": "Casanare",
    "municipios": [
      "Aguazul",
      "Chámeza",
      "Hato Corozal",
      "La Salina",
      "Maní",
      "Monterrey",
      "Nunchía",
      "Orocué",
      "Paz de Ariporo",
      "Pore",
      "Recetor",
      "Sabanalarga",
      "Sácama",
      "San Luis de Palenque",
      "Támara",
      "Tauramena",
      "Trinidad",
      "Villanueva",
      "Yopal",
    ],
  },
  {
    "nombre": "Cauca",
    "municipios": [
      "Buenos Aires",
      "Caloto",
      "Corinto",
      "Guachené",
      "Miranda",
      "Padilla",
      "Puerto Tejada",
      "Santander de Quilichao",
      "Suárez",
      "Villa Rica",
      "Cajibío",
      "El Tambo",
      "La Sierra",
      "Morales",
      "Piendamó",
      "Popayán",
      "Rosas",
      "Sotará",
      "Timbío",
      "Almaguer",
      "Argelia",
      "Balboa",
      "Bolívar",
      "Florencia",
      "La Vega",
      "Mercaderes",
      "Patía",
      "Piamonte",
      "San Sebastián",
      "Santa Rosa",
      "Sucre",
      "Guapi",
      "López de Micay",
      "Timbiquí",
      "Caldono",
      "Inzá",
      "Jambaló",
      "Páez",
      "Puracé - Coconuco",
      "Silvia",
      "Toribío",
      "Totoró",
    ],
  },
  {
    "nombre": "Cesar",
    "municipios": [
      "Valledupar",
      "Aguachica",
      "Agustín Codazzi",
      "Bosconia",
      "Chimichagua",
      "El Copey",
      "San Alberto",
      "Curumaní",
      "El Paso",
      "La Paz",
      "Pueblo Bello",
      "La Jagua de Ibirico",
      "Chiriguaná",
      "Astrea",
      "San Martín",
      "Pelaya",
      "Pailitas",
      "Gamarra",
      "Manaure",
      "Río de Oro",
      "Tamalameque",
      "Becerril",
      "San Diego",
      "La Gloria",
      "González",
    ],
  },
  {
    "nombre": "Chocó",
    "municipios": [
      "Acandí",
      "Alto Baudó",
      "Atrato",
      "Bagadó",
      "Bahía Solano",
      "Bajo Baudó",
      "Bojayá",
      "Cértegui",
      "Condoto",
      "El Cantón de San Pablo",
      "El Carmen de Atrato",
      "El Carmen del Darién",
      "El Litoral de San Juan",
      "Istmina",
      "Juradó",
      "Lloró",
      "Medio Atrato",
      "Medio Baudó",
      "Medio San Juan",
      "Nóvita",
      "Nuquí",
      "Quibdó",
      "Río Iró",
      "Río Quito",
      "Riosucio",
      "San José del Palmar",
      "Sipí",
      "Tadó",
      "Unguía",
      "Unión Panamericana",
    ],
  },
  {
    "nombre": "Córdoba",
    "municipios": [
      "Ayapel",
      "Buenavista",
      "Canalete",
      "Cereté",
      "Chimá",
      "Chinú",
      "Ciénaga de Oro",
      "Cotorra",
      "La Apartada",
      "Los Córdobas",
      "Momil",
      "Montelíbano",
      "Montería",
      "Moñitos",
      "Planeta Rica",
      "Pueblo Nuevo",
      "Puerto Escondido",
      "Puerto Libertador",
      "Purísima",
      "Sahagún",
      "San Andrés de Sotavento",
      "San Antero",
      "San Bernardo del Viento",
      "San Carlos",
      "San José de Uré",
      "San Pelayo",
      "Santa Cruz de Lorica",
      "Tierralta",
      "Tuchín",
      "Valencia",
    ],
  },
  {
    "nombre": "Cundinamarca",
    "municipios": [
      "Chocontá",
      "Machetá",
      "Manta",
      "Sesquilé",
      "Suesca",
      "Tibirita",
      "Villapinzón",
      "Agua de Dios",
      "Girardot",
      "Guataquí",
      "Jerusalén",
      "Nariño",
      "Nilo",
      "Ricaurte",
      "Tocaima",
      "Caparrapí",
      "Guaduas",
      "Puerto Salgar",
      "Albán",
      "La Peña",
      "La Vega",
      "Nimaima",
      "Nocaima",
      "Quebradanegra",
      "San Francisco",
      "Sasaima",
      "Supatá",
      "Útica",
      "Vergara",
      "Villeta",
      "Gachalá",
      "Gachetá",
      "Gama",
      "Guasca",
      "Guatavita",
      "Junín",
      "La Calera",
      "Ubalá",
      "Beltrán",
      "Bituima",
      "Chaguaní",
      "Guayabal de Síquima",
      "Pulí",
      "San Juan de Rioseco",
      "Vianí",
      "Medina",
      "Paratebueno",
      "Cáqueza",
      "Chipaque",
      "Choachí",
      "Fómeque",
      "Fosca",
      "Guayabetal",
      "Gutiérrez",
      "Quetame",
      "Ubaque",
      "Une",
      "El Peñón",
      "La Palma",
      "Pacho",
      "Paime",
      "San Cayetano",
      "Topaipí",
      "Villagómez",
      "Yacopí",
      "Cajicá",
      "Chía",
      "Cogua",
      "Cota",
      "Gachancipá",
      "Nemocón",
      "Sopó",
      "Tabio",
      "Tenjo",
      "Tocancipá",
      "Zipaquirá",
      "Bojacá",
      "El Rosal",
      "Facatativá",
      "Funza",
      "Madrid",
      "Mosquera",
      "Subachoque",
      "Zipacón",
      "Sibaté",
      "Soacha",
      "Arbeláez",
      "Cabrera",
      "Fusagasugá",
      "Granada",
      "Pandi",
      "Pasca",
      "San Bernardo",
      "Silvania",
      "Tibacuy",
      "Venecia",
      "Anapoima",
      "Anolaima",
      "Apulo",
      "Cachipay",
      "El Colegio",
      "La Mesa",
      "Quipile",
      "San Antonio del Tequendama",
      "Tena",
      "Viotá",
      "Carmen de Carupa",
      "Cucunubá",
      "Fúquene",
      "Guachetá",
      "Lenguazaque",
      "Simijaca",
      "Susa",
      "Sutatausa",
      "Tausa",
      "Ubaté",
    ],
  },
  {
    "nombre": "Guainía",
    "municipios": [
      "Barrancominas",
      "Cacahual",
      "Inírida",
      "La Guadalupe",
      "Morichal Nuevo",
      "Pana Pana",
      "Puerto Colombia",
      "San Felipe",
    ],
  },
  {
    "nombre": "Guaviare",
    "municipios": [
      "Calamar",
      "El Retorno",
      "Miraflores",
      "San José del Guaviare",
    ],
  },
  {
    "nombre": "Huila",
    "municipios": [
      "Acevedo",
      "Aipe",
      "Algeciras",
      "Altamira",
      "Baraya",
      "Campoalegre",
      "Colombia",
      "Elías",
      "El Agrado",
      "Garzón",
      "Gigante",
      "Guadalupe",
      "Hobo",
      "Íquira",
      "Isnos",
      "La Argentina",
      "La Plata",
      "Nátaga",
      "Neiva",
      "Oporapa",
      "Paicol",
      "Palermo",
      "Palestina",
      "Pital",
      "Pitalito",
      "Rivera",
      "Saladoblanco",
      "Santa María",
      "San Agustín",
      "Suaza",
      "Tarqui",
      "Tello",
      "Teruel",
      "Tesalia",
      "Timaná",
      "Villavieja",
      "Yaguará",
    ],
  },
  {
    "nombre": "La Guajira",
    "municipios": [
      "Albania",
      "Barrancas",
      "Dibulla",
      "Distracción",
      "El Molino",
      "Fonseca",
      "Hatonuevo",
      "La Jagua del Pilar",
      "Maicao",
      "Manaure",
      "Riohacha",
      "San Juan del Cesar",
      "Uribia",
      "Urumita",
      "Villanueva",
    ],
  },
  {
    "nombre": "Magdalena",
    "municipios": [
      "Algarrobo",
      "Aracataca",
      "Ariguaní",
      "Cerro de San Antonio",
      "Chibolo",
      "Ciénaga",
      "Concordia",
      "El Banco",
      "El Piñón",
      "El Retén",
      "Fundación",
      "Guamal",
      "Nueva Granada",
      "Pedraza",
      "Pijiño del Carmen",
      "Pivijay",
      "Plato",
      "Pueblo Viejo",
      "Remolino",
      "Sabanas de San Ángel",
      "Salamina",
      "San Sebastián de Buenavista",
      "Santa Ana",
      "Santa Bárbara de Pinto",
      "Santa Marta",
      "San Zenón",
      "Sitionuevo",
      "Tenerife",
      "Zapayán",
      "Zona Bananera",
    ],
  },
  {
    "nombre": "Meta",
    "municipios": [
      "Acacías",
      "Barranca de Upía",
      "Cabuyaro",
      "Castilla La Nueva",
      "Cubarral",
      "Cumaral",
      "El Calvario",
      "El Castillo",
      "El Dorado",
      "Fuente de Oro",
      "Granada",
      "Guamal",
      "La Macarena",
      "La Uribe",
      "Lejanías",
      "Mapiripán",
      "Mesetas",
      "Puerto Concordia",
      "Puerto Gaitán",
      "Puerto Lleras",
      "Puerto López",
      "Puerto Rico",
      "Restrepo",
      "San Carlos de Guaroa",
      "San Juan de Arama",
      "San Juanito",
      "San Martín",
      "Villavicencio",
      "Vista Hermosa",
    ],
  },
  {
    "nombre": "Nariño",
    "municipios": [
      "Barbacoas",
      "El Charco",
      "Francisco Pizarro",
      "La Tola",
      "Magüí Payán",
      "Mosquera",
      "Olaya Herrera",
      "Roberto Payán",
      "Santa Bárbara",
      "Tumaco",
      "Aldana",
      "Contadero",
      "Córdoba",
      "Cuaspud",
      "Cumbal",
      "Funes",
      "Guachucal",
      "Gualmatán",
      "Iles",
      "Ipiales",
      "Potosí",
      "Puerres",
      "Pupiales",
      "Albán",
      "Arboleda",
      "Belén",
      "Colón",
      "El Rosario",
      "El Tablón de Gómez",
      "La Cruz",
      "La Unión",
      "Leiva",
      "Policarpa",
      "San Bernardo",
      "San Lorenzo",
      "San Pablo",
      "San Pedro de Cartago",
      "Taminango",
      "Buesaco",
      "Chachagüí",
      "Consacá",
      "El Peñol",
      "El Tambo",
      "La Florida",
      "Nariño",
      "Pasto",
      "Sandoná",
      "Tangua",
      "Yacuanquer",
      "Ancuya",
      "Cumbitara",
      "Guaitarilla",
      "Imués",
      "La Llanada",
      "Linares",
      "Los Andes",
      "Mallama",
      "Ospina",
      "Providencia",
      "Ricaurte",
      "Samaniego",
      "Santacruz",
      "Sapuyes",
      "Túquerres",
    ],
  },
  {
    "nombre": "Norte de Santander",
    "municipios": [
      "Arboledas",
      "Cucutilla",
      "Gramalote",
      "Lourdes",
      "Salazar de Las Palmas",
      "Santiago",
      "Villa Caro",
      "Cúcuta",
      "El Zulia",
      "Los Patios",
      "Puerto Santander",
      "San Cayetano",
      "Villa del Rosario",
      "Bucarasica",
      "El Tarra",
      "Sardinata",
      "Tibú",
      "Ábrego",
      "Cáchira",
      "Convención",
      "El Carmen",
      "Hacarí",
      "La Esperanza",
      "La Playa de Belén",
      "Ocaña",
      "San Calixto",
      "Teorama",
      "Cácota",
      "Chitagá",
      "Mutiscua",
      "Pamplona",
      "Pamplonita",
      "Santo Domingo de Silos",
      "Bochalema",
      "Chinácota",
      "Durania",
      "Herrán",
      "Labateca",
      "Ragonvalia",
      "Toledo",
    ],
  },
  {
    "nombre": "Putumayo",
    "municipios": [
      "Colón",
      "Mocoa",
      "Orito",
      "Puerto Asís",
      "Puerto Caicedo",
      "Puerto Guzmán",
      "Puerto Leguízamo",
      "San Francisco",
      "San Miguel",
      "Santiago",
      "Sibundoy",
      "Valle del Guamuez",
      "Villagarzón",
    ],
  },
  {
    "nombre": "Quindío",
    "municipios": [
      "Armenia",
      "Buenavista",
      "Calarcá",
      "Circasia",
      "Córdoba",
      "Filandia",
      "Génova",
      "La Tebaida",
      "Montenegro",
      "Pijao",
      "Quimbaya",
      "Salento",
    ],
  },
  {
    "nombre": "Risaralda",
    "municipios": [
      "Apía",
      "Balboa",
      "Belén de Umbría",
      "Dosquebradas",
      "Guática",
      "La Celia",
      "La Virginia",
      "Marsella",
      "Mistrató",
      "Pereira",
      "Pueblo Rico",
      "Quinchía",
      "Santa Rosa de Cabal",
      "Santuario",
    ],
  },
  {
    "nombre": "San Andrés y Providencia",
    "municipios": ["San andres", "Providencia"],
  },
  {
    "nombre": "Santander",
    "municipios": [
      "Aguada",
      "Albania",
      "Aratoca",
      "Barbosa",
      "Barichara",
      "Barrancabermeja",
      "Betulia",
      "Bolívar",
      "Bucaramanga",
      "Cabrera",
      "California",
      "Capitanejo",
      "Carcasí",
      "Cepitá",
      "Cerrito",
      "Charalá",
      "Charta",
      "Chima",
      "Chipatá",
      "Cimitarra",
      "Concepción",
      "Confines",
      "Contratación",
      "Coromoro",
      "Curití",
      "El Carmen de Chucurí",
      "El Guacamayo",
      "El Peñón",
      "El Playón",
      "Encino",
      "Enciso",
      "Florián",
      "Floridablanca",
      "Galán",
      "Gámbita",
      "Girón",
      "Guaca",
      "Guadalupe",
      "Guapotá",
      "Guavatá",
      "Güepsa",
      "Hato",
      "Jesús María",
      "Jordán",
      "La Belleza",
      "La Paz",
      "Landázuri",
      "Lebrija",
      "Los Santos",
      "Macaravita",
      "Málaga",
      "Matanza",
      "Mogotes",
      "Molagavita",
      "Ocamonte",
      "Oiba",
      "Onzaga",
      "Palmar",
      "Palmas del Socorro",
      "Páramo",
      "Piedecuesta",
      "Pinchote",
      "Puente Nacional",
      "Puerto Parra",
      "Puerto Wilches",
      "Rionegro",
      "Sabana de Torres",
      "San Andrés",
      "San Benito",
      "San Gil",
      "San Joaquín",
      "San José de Miranda",
      "San Miguel",
      "San Vicente de Chucurí",
      "Santa Bárbara",
      "Santa Helena del Opón",
      "Simacota",
      "Socorro",
      "Suaita",
      "Sucre",
      "Suratá",
      "Tona",
      "Valle de San José",
      "Vélez",
      "Vetas",
      "Villanueva",
      "Zapatoca",
    ],
  },
  {
    "nombre": "Sucre",
    "municipios": [
      "Guaranda",
      "Majagual",
      "Sucre",
      "Chalán",
      "Colosó",
      "Morroa",
      "Ovejas",
      "Sincelejo",
      "Coveñas",
      "Palmito",
      "San Onofre",
      "Santiago de Tolú",
      "Toluviejo",
      "Buenavista",
      "Corozal",
      "El Roble",
      "Galeras",
      "Los Palmitos",
      "Sampués",
      "San Juan de Betulia",
      "San Pedro",
      "Sincé",
      "Caimito",
      "La Unión",
      "San Benito Abad",
      "San Marcos",
    ],
  },
  {
    "nombre": "Tolima",
    "municipios": [
      "Alvarado",
      "Anzoátegui",
      "Cajamarca",
      "Coello",
      "Espinal",
      "Flandes",
      "Ibagué",
      "Piedras",
      "Rovira",
      "San Luis",
      "Valle de San Juan",
      "Casabianca",
      "Herveo",
      "Lérida",
      "Líbano",
      "Murillo",
      "Santa Isabel",
      "Venadillo",
      "Villahermosa",
      "Ambalema",
      "Armero",
      "Falan",
      "Fresno",
      "Honda",
      "Mariquita",
      "Palocabildo",
      "Carmen de Apicalá",
      "Cunday",
      "Icononzo",
      "Melgar",
      "Villarrica",
      "Ataco",
      "Chaparral",
      "Coyaima",
      "Natagaima",
      "Ortega",
      "Planadas",
      "Rioblanco",
      "Roncesvalles",
      "San Antonio",
      "Alpujarra",
      "Dolores",
      "Guamo",
      "Prado",
      "Purificación",
      "Saldaña",
      "Suárez",
    ],
  },
  {
    "nombre": "Valle del Cauca",
    "municipios": [
      "Alcalá",
      "Andalucía",
      "Ansermanuevo",
      "Argelia",
      "Bolívar",
      "Buenaventura",
      "Buga",
      "Bugalagrande",
      "Caicedonia",
      "Cali",
      "Calima - El Darién",
      "Candelaria",
      "Cartago",
      "Dagua",
      "El Águila",
      "El Cairo",
      "El Cerrito",
      "El Dovio",
      "Florida",
      "Ginebra",
      "Guacarí",
      "Jamundí",
      "La Cumbre",
      "La Unión",
      "La Victoria",
      "Obando",
      "Palmira",
      "Pradera",
      "Restrepo",
      "Riofrío",
      "Roldanillo",
      "San Pedro",
      "Sevilla",
      "Toro",
      "Trujillo",
      "Tuluá",
      "Ulloa",
      "Versalles",
      "Vijes",
      "Yotoco",
      "Yumbo",
      "Zarzal",
    ],
  },
  {
    "nombre": "Vaupés",
    "municipios": [
      "Carurú",
      "Mitú",
      "Pacoa",
      "Papunaua",
      "Taraira",
      "Yavaraté",
    ],
  },
  {
    "nombre": "Vichada",
    "municipios": [
      "Cumaribo",
      "La Primavera",
      "Puerto Carreño",
      "Santa Rosalía",
    ],
  },
];
